### ISSUE TITLE
Ignore string inside Symbol('description')

### ISSUE THREAD

**Issue by vitalets** [stryker-mutator/stryker-js#2152]
**Is your feature request related to a problem? Please describe.**
Currently I'm getting many errors like this:
```
[Survived] StringLiteral
-   const hasInitialTitle = Symbol('hasInitialTitle');
+   const hasInitialTitle = Symbol("");
```

According to MDN [Symbol() description is optional and used only for debugging](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol).
So there is not need to check it in tests and via stryker.

**Describe the solution you'd like**
Just don't mutate strings inside `Symbol()` constructor.

**Additional context**
```
    "@stryker-mutator/core": "^3.1.0",
    "@stryker-mutator/javascript-mutator": "^3.1.0",
    "@stryker-mutator/mocha-framework": "^3.1.0",
    "@stryker-mutator/mocha-runner": "^3.1.0",
```

**Comment by nicojs** [comment]
Hi @vitalets 🙋‍♂️

Yeah, sounds reasonable. Thanks for the feature request. ❤ We'll be implementing this.

**Comment by Galus** [comment]
I have this issue with the node-debug library. When writing the equivalent of a console.debug() with the node-debug library, I write: debug("My debug log") and each of these get mutated and show up in the reports. Looking for a way to disable them on this Symbol led me here.

**Comment by Galus** [comment]
Many related issues, but this one is related: https://github.com/stryker-mutator/stryker/issues/1472

**Comment by nicojs** [comment]
As for the `debug` library, I would argue that I want those to be mutated. If someone changes a debug logline, I would want a test to fail. At least, it is important enough. We will be implementing #1472 as @Galus pointed out, so then you can ignore it.

I would say `Symbol()` is different since it is purely there for readability. Every Symbol is unique and it doesn't make a ton of sense to start testing the `Symbol.prototype.description`. 

As a workaround, you could add tests for the descriptions I guess. 🤔
