### ISSUE TITLE
Execute mutation testing despite of failing tests.

### ISSUE THREAD

**Issue by Tummerhore** [stryker-mutator/stryker-js#2273]
Currently if at least one test failes during the inital test run, Stryker exits with an error and without doing the actual mutation testing.
I suggest an option (e.g ` skipFailingTests: true | false`) which marks failing tests during the initial test run as "skipped" so that Stryker can continue with the remanining working tests for the actual mutation testing. This would be very helpful for long test suites which contain some flaky tests: Here, the inital test run can take quite some time (> 3m) and it's quite annoying to wait for the initial test run multiple times until it suceeds, although one test more or less would not dramatically alter the mutation score.

**Comment by nicojs** [comment]
Hmm interesting.

> This would be very helpful for long test suites which contain some flaky tests

Test suites with flaky tests are a big problem in general, but especially if used with mutation testing. Mutants might accidentally get killed, just because of a flaky test. I strongly advise you to invest the time it takes to figure out why your suite is flaky in the first place. 

If they are flaky 'by design' than I would advise disabling those tests for mutation testing. Examples of 'by design' flakiness: 
* Timing dependent tests and might fail when your CPU is under a different load than normal
* Integration tests that run on a database that you also use to demo your project.

Your suggestion to mark the failing test with 'skipped' would only work with test runners that support test filtering. Currently, `@stryker-mutator/jest-runner` and `@stryker-mutator/wct-runner` don't support test filtering. I'm hesitant to add a feature that only works with some of our plugins.

**Comment by Tummerhore** [comment]
Thanks for your reply. You're right that flaky tests are not ideal. But I would also see it helpful for other situations: There can be times when some tests will always fail but you want to know the mutation score with the remaining working tests. (One could then manually leave these tests out but that's an additional step to do and it would be much nicer if Stryker could automatically handle it for you.)

Regarding the marking of tests as "skipped": This was just an idea, how I think this could be easily implemented. You said that the jest-runner doesn't support test filtering which I don't quite understand. Why not just modify the failing tests from
`test(name, fn)` to `test.skip(name, fn)` in Stryker's sandbox?
