### ISSUE TITLE
Search for config file in parent folder

### ISSUE THREAD

**Issue by Tummerhore** [stryker-mutator/stryker-js#2371]
When using stryker in a monorepo it's helpful to have a common stryker config in a parent folder which can be overwritten by configs in the sub packages if necessary.
```
├── package.json
├── packages
│   ├── pack1
│   │   ├── package.json
│   │   └── stryker.conf.json
│   ├── pack2
│   │   ├── package.json
│   │   └── stryker.conf.json
│   ├── pack3
│   │   ├── package.json
│   │   └── stryker.conf.json
├── stryker.parent.conf.js
```

However, if I don't want to overwrite it I still have to include an additional package config file which only includes the parent config like this:
```
module.exports = require('../../stryker.parent.conf')
```

It would be great if stryker does automatically look for config files in parent folders if no config can be found in the current working directory.

**Comment by nicojs** [comment]
How would you expect this work exactly?

If you run `stryker run` inside `parent/packages/child`, look for `stryker.conf` inside the current dir. If not found, walk up until you find one. I understand that part.

What should happen if a `stryker.conf` file is found inside `parent`? For example, it specifies `{ "mutate}: ['src/**/*.ts'] }`, should that globbing expression be done from `parent`? Or from the cwd? The same goes file discovery, sandbox directory location, etc.

**Comment by Tummerhore** [comment]
Good question. I would have handled the paths relative to the cwd. So basically, it just works like explicitly specified config files are handled right now. Let's say we are currently running `stryker run  ../../stryker.json`  but with the new feature we can also just do `stryker run` and leave the paths in the config file unchanged.

**Comment by nicojs** [comment]
I have to be honest, I don't know if this is expected behavior. When loading a project file from a directory, one might expect the files to be resolved from that directory. 

This is what we had in mind with a "baseDir" or "projectRoot" configuration. We closed this issue later, because of time constraints, but I would still like a "baseDir" option: #650

In that case `stryker run --baseDir . ../../stryker.json` would work and after this change is merged this should work: `stryker run --baseDir .`. But this would not work `stryker run` (since that would resolve files from `../..`).
