### ISSUE TITLE
replace `export default` with `export`

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker-js#2373]
using export while defining a variable, function, class, enum etc. increases the readability, since you know from the start that it is exported. You dont need to look for it later in the code.

`export default` is not working with some objects like enum or type.

Changing all `export default` also would make code more consistent.

The only downside is in files with only one `export`, especially with its name the same as file name, since `export default` and `import name from './name'` makes the most sense in that case.

I would still opt for using plain `export` due to IMO easier maintenance and readability.

**Comment by nicojs** [comment]
Agreed. Maybe fix this together with #1588 ?

**Comment by kmdrGroch** [comment]
Can do :)

**Comment by kmdrGroch** [comment]
Just after my current PR I can proceed to this one

**Comment by nicojs** [comment]
Just gave some feedback. 

If you're going through all the files, would you mind also enabling https://www.typescriptlang.org/tsconfig#esModuleInterop

This allows us to use default imports from common js modules. For example: `import path from 'path'` or `import sinon from 'sinon'`. This is in line with how babel transpiles as well, and it is the way how nodejs will resolve imports with es module - commonjs interop.

After enabling `esModuleInterop`, you should get compiler errors for `import * as path from 'path'`, however `import path = require('path');` would still be valid. I would personally prefer the default imports: `import path from 'path'`, since it is in line with es spec. 😇

**Comment by kmdrGroch** [comment]
So basically fix all possible import / export problems :) cool with me
