### ISSUE TITLE
cannot run stryker from mocha itself

### ISSUE THREAD

**Issue by boneskull** [stryker-mutator/stryker-js#2414]
**Summary**

I thought I'd take a closer look a stryker for use in Mocha, but couldn't get very far. 😄

When attempting to run Stryker in a working copy of `mocha`, the `@stryker-mutator/mocha-runner` plugin cannot be found, even though it's installed.

**Stryker config**

```js
'use strict';

/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  mutator: 'javascript',
  packageManager: 'npm',
  reporters: ['html', 'clear-text', 'progress'],
  testRunner: 'mocha',
  transpilers: [],
  testFramework: 'mocha',
  coverageAnalysis: 'perTest'
};
```

**Test runner config**

```yaml
  require: 'test/setup'
  ui: 'bdd'
  global:
    - 'okGlobalA,okGlobalB'
    - 'okGlobalC'
    - 'callback*'
  timeout: 1000
  watch-ignore:
    - '**/.*/**'
    - 'docs/_dist/**'
    - 'docs/_site/**'
    - '**/node_modules/**'
    - '**/coverage/**'
```

**Stryker environment**

```
npm ERR! peer dep missing: mocha@>= 2.3.3 < 8, required by @stryker-mutator/mocha-framework@3.3.1
npm ERR! peer dep missing: mocha@>= 2.3.3 < 9, required by @stryker-mutator/mocha-runner@3.3.1
├─┬ @stryker-mutator/core@3.3.1
│ ├─┬ @stryker-mutator/api@3.3.1
│ ├── @stryker-mutator/util@3.3.1
├─┬ @stryker-mutator/javascript-mutator@3.3.1
│ ├── @stryker-mutator/api@3.3.1 deduped
├─┬ @stryker-mutator/mocha-framework@3.3.1
│ ├── @stryker-mutator/api@3.3.1 deduped
│ └── @stryker-mutator/util@3.3.1 deduped
├─┬ @stryker-mutator/mocha-runner@3.3.1
│ ├── @stryker-mutator/api@3.3.1 deduped
│ ├── @stryker-mutator/util@3.3.1 deduped
├─┬ stryker-cli@1.0.0
```

Mocha cannot/will not install `mocha` as a `devDependency` of itself--that peer dep check will always fail.  `NODE_PATH=.` _usually_ works for this sort of thing, but perhaps the plugin(s) aren't respecting it.  If it _should_ work, then this is a bug, but if it shouldn't, it's a missing feature ("ability to specify path to mocha module").

**Test runner environment**

many, but this is an example:

```shell
bin/mocha "test/node-unit/**/*.spec.js" "test/unit/**/*.spec.js"
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 14.3.0
| npm              | 6.14.7
| Operating System | macOS 10.15.5

**Add stryker.log**

The gist below contains two log files; one without `NODE_PATH` set, and another with `NODE_PATH` set.  Results are nearly identical (but not entirely identical).

https://gist.github.com/boneskull/3704e2768371580b5808ef7d26564b0a

(Also note that Stryker complains about the Mocha version, for some reason)

**Comment by nicojs** [comment]
Hi there @boneskull 👋, welcome to our corner of the internet 😅.

> `NODE_PATH=`. _usually_ works for this sort of thing

Hmm, interesting... I haven't thought of that. I think these deep imports might cause a problem:

https://github.com/stryker-mutator/stryker/blob/2eec539ddaffa9fd65eaf1413ab29885a45ea510/packages/mocha-runner/src/LibWrapper.ts#L17

https://github.com/stryker-mutator/stryker/blob/2eec539ddaffa9fd65eaf1413ab29885a45ea510/packages/mocha-runner/src/LibWrapper.ts#L24

https://github.com/stryker-mutator/stryker/blob/2eec539ddaffa9fd65eaf1413ab29885a45ea510/packages/mocha-runner/src/LibWrapper.ts#L31

In fact, when the import on line 17 fails, you get this warning (as seen in your logs)

> DEPRECATED: Mocha < 6 detected. Please upgrade to at least Mocha version 6.

Does the `NODE_PATH=` solution not work with these deep imports?

However, the `@stryker-mutator/mocha-runner` should still work, because it would fall back to "interop mode". This error is the reason Stryker eventually crashes:

> Cause: Cannot load TestRunner plugin "mocha". In fact, no TestRunner plugins were loaded. Did you forget to install it?

This means something went wrong with importing `mocha` in the child process. Probably again has to do with `NODE_PATH`. What is the value you're using for it? Then I can test it out myself and see what's wrong. 

I've also been thinking about how we could use Stryker to run on Mocha itself. Instead of using `NODE_PATH`, I was thinking to add a configuration option to point to a different mocha installation. For example:

```js
{
  "mocha": {
     "instance": __dirname
   }
}
```

However, if we can make it work with `NODE_PATH`, then I think that would be preferred since running Stryker on mocha would be the only use case I can see for overriding mocha.instance. However, if the deep imports are the problem, then I think we should first implement https://github.com/mochajs/mocha/issues/3882 so we can use a public API to create, configure, and run mocha. 🤷‍♂️
