### ISSUE TITLE
[Discussion, WIP] Made it easier to report bugs

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker-js#2723]
### General problem
Nowadays Stryker is sending out a lot of information, and a lot of information about Stryker is in several places - package.json, stryker.conf, reports, logs. That much of data can sometimes be tricky to handle, filter and use - which makes it time consuming and more importantly, confusing.

### Example
Imagine you have an issue with Stryker. What do you do?

Open an issue tab and click on a bug template and then you see the huge amount of data we want from you. Summary? Config? But you need to change paths, because you can't leak them... Then some other configs... Again some changes? Stryker environment... Come on... Give me a break... And it keeps on going... Oww and do not forget about Stryker.log which is soomewhere in your code base. But you also forgot to specify debug mode...

Or you just copy paste output from console and everything is good right? Or even just "error: "stryker does not work".
It is understandable. You want a bug to be fixed not to send us thousands of lines with confidential information which has to be trimmed... Let's not start again...

### Conclusion
It is a problem that needs a proper action to be taken.

### Solutions to this problem
An uniform, (potentially one file) reporting system. One file to send, and all information about bug should be there (or at least enough information). Nothing more. Nothing less.

Possible method:
- JSON reporter - information about mutations (without details about specific source code), environment (system information [only important {for us} bits - no personal information such as computer name would be exposed!], versions of Node, stryker, test runners, etc), configs (stryker, test runner).
- In case of a bug (stryker did not finish the run), automatic stryker.log creation in debug-secure mode (the power of debug, the security of privacy) (unless specified otherwise) - basically rerun a task with additional flag "debug" and "secure" (unless --debug or other mode used during a run) - which is ready-to-send to us without worrying about leaking private information.
In case of debug mode, information from JSON reporter should be included, see above.
Only stryker.log would be a file to be sent.

Unfortunatelly for the successful run, but with issue, for example in report, stryker would need to be executed once more, with appropiate flags.
JSON report and stryker.log would be files to be sent.

**Comment by kmdrGroch** [comment]
@nicojs, @simondel, @Garethp and of course others - users or potential maintainers have some ideas, questions, etc. feel free to add/ask/join discussion :)

**Comment by nicojs** [comment]
I agree we should make it easier to collect all the information. However, I don't want to spend too much time on it, I would rather spend the time improving error messages, ease of use, and troubleshooting guides (btw, we need a troubleshooting guide 🌠).

Let's add a simple command to Stryker. For example: `stryker env`. When you run this command, it prints all relevant info to the console, ready for you to copy-paste it into your issue. It can include configuration, dependencies and their versions, info about CPU and OS information. However, it won't contain information details about your issue. For that, we might still want to have the debug logging.

Some additional `--secure` flag might be tricky to implement -- what is a secret? By simply removing all file information it might get hard to debug the issue. And not everyone would care if we get their file names, right? The JSON report itself contains all file contents, so that would be a much bigger risk.
