### ISSUE TITLE
Mutate `??`

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker-js#2876]
**Is your feature request related to a problem? Please describe.**
StrykerJS mutates `||` to `&&`, but it does nothing with `??`. This is hugely frustrating for me.

**Describe the solution you'd like**
StrykerJS could mutate `??` to `||`

**Describe alternatives you've considered**
Changing code manually and running tests. But this is a little slow.

**Additional context**
Should StrykerJS always mutate `??`? It might sometime result in a non-killable mutant. And what about the other way around? The syntax might not always be supported.

**Comment by kmdrGroch** [comment]
`??` is just sugarcoated `a !== null && a !== undefined`...
```js
r = a ?? b;
r = (a !== null && a !== undefined) ? a : b;
```

so there is no problem with support I guess, since this would be work around.

non-killable mutant... yeaa... it might generate equivalent mutants yea...
i mean... if you were to check `0` or `""` i might generate good mutant
since
`0 ?? b` and `0 || b` would generate sth different
tho if you have type
`null | object`
then you can't possibly test it...
then only option would be
`0 ?? b` -> `0 && b` i believe

**Comment by nicojs** [comment]
Yeah, I think `&&` is the best thing to do. Q: What should we do with the optional chaining operator?

`foo?,bar`
`foo?.[1]`
`foo?.()`

**Comment by kmdrGroch** [comment]
I believe so... We could also think about changing ? to !...
That leaves ! too. We could potentially remove it or do ?

**Comment by nicojs** [comment]
What do you mean exactly @kmdrGroch? Mutate `foo?.bar` to `foo!.bar` instead of `foo.bar`? 

I don't like that approach, because that would only work in TypeScript files. Right now, all our mutators are TS independent and I would like to keep them that way.

Also: `foo.bar` is identical in meaning to `foo!.bar`, except when using TypeScripts type checker. We turn that type checker _off_ for mutation testing (by inserting `// @ts-nocheck` in each file). The only place it would make a difference is when using the `@stryker-mutator/typescript-checker`, it would possibly mark the mutant as "CompileError". That is fine IMO, TypeScript devs don't have to write as many tests as plain JS devs, because of the magic of TypeScript 🤷‍♂️.

**Comment by nicojs** [comment]
I've started working on this. Adding the `??` was surprisingly simple: #2884

I've asked in the mutation-testing-elements slack channel in our Stryker slack for help with the optional chaining bit. Namely: "Is it a good idea?" and "What should the mutator be named?". 

Naming new mutators is something that has to be aligned with all Stryker versions.

Might need to post pone till after the 5.0 release.

**Comment by nicojs** [comment]
Long since implemented
