### ISSUE TITLE
Epic Maintenance task: Refactor and clean up stuff

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker-js#2883]
Well... We are going closer and closer to v5 release. Our database is growing, features are coming. I believe it is a time to refactor stuff so we are not lost in the future.

Stuff to be considered:
- reconsidering what tools we are using: CI/CD github stuff, e.x #2631 for dependabot. Double check if there will be some changes in the future - e.x possible node drop.
- lint (again). Try to fix the issues we have (see .eslintrc) + #2745
- overall refactoring - some functions are "thicc". We would try using eslint to, e.x set max allowed function size to 100 lines (could try reducing it in the future - to 40 [should still be smaller but yeaa]) -- see videos from that cycle: https://www.youtube.com/watch?v=7EmboKQH8lM

Since we are getting more and more users and more and more maintainers (well... kinda), making code clean and easy to maintain could significantly improve time and difficulty of implementing new features / removing bugs etc. (see #2877 - 33 files changed + removing a feature actually increased the size of the project!)

I know there is a lot stuff to be considered, so potentially in the comments below we could think of stuff, that could be implemented and make a list, just like we have for milestones, see #2721)

**Comment by kmdrGroch** [comment]
so first: Linting stuff

[] @typescript-eslint/naming-convention
[] @typescript-eslint/require-await
[] @typescript-eslint/promise-function-async
[] @typescript-eslint/no-misused-promises
[] @typescript-eslint/return-await
[] @typescript-eslint/await-thenable
[] @typescript-eslint/no-floating-promises
[] @typescript-eslint/unbound-method
[] @typescript-eslint/no-unnecessary-condition
[] @typescript-eslint/no-base-to-string
[] @typescript-eslint/init-declarations
[] @typescript-eslint/no-explicit-any
[] @typescript-eslint/no-magic-numbers

second functions and files style:
- line width should be length max 100
- function length max 100 (with future decrease) - that would mean we would have more modularity
- try avoiding switch statements - however that sounds, in the talk it is nicely justified - e.x changing one element in enum would require us to go to all switch statements related to that enum and check/add to them
- more meaningful names - no comments are required that way - see stryker.ts - we tried and almost did it. (that should be globally implemented - while most of names are not the problem I believe, we could improve them in some places)
- reduce the cognitive complexity

**Comment by nicojs** [comment]
> We are going closer and closer to v5 release.

Do you want to get this in before v5 release? I don't want to add more TBH, working hard to get it released.

> reconsidering what tools we are using: CI/CD github stuff

What do you mean exactly? I'm happy with our current choices (dependabot + GH actions). The reason I didn't merge dependabot config file yet, is because that would stop dependabot from merging dev-dependency updates automatically. Feel free to update the config, merge it and add the mergify bot for automatic merging of dev deps https://mergify.io/

> try avoiding switch statements - however that sounds, in the talk it is nicely justified - e.x changing one element in enum would require us to go to all switch statements related to that enum and check/add to them

I disagree with this since TypeScript supports [exhaustiveness checking](https://dev.to/babak/exhaustive-type-checking-with-typescript-4l3f). Adding or removing an enum value leads to a compiler error. TS is awesome like that.

> some functions are "thicc".

Sure, there probably are some that can be fixed with refactoring. However, function length only isn't the best indicator, it is about the level of abstraction. Take `stryker-cli.ts` for example. A big function, but I feel like it is at the correct level of abstraction. Splitting it would just make it harder to understand what is happening. 

> more meaningful names 

I'm open to suggestions! I've always preached this practice myself and I think we did a pretty good job so far (I hope). 

> reduce the cognitive complexity

Do you have specific places in mind? I personally feel pretty happy with this myself.

And, oh yeah, please make small PRs for this! 😅

**Comment by kmdrGroch** [comment]
It would be more in V6 roadmap.

By CI/CD I only meant to check them if they are up to date :)

I also have problems with `switch` statements. It could potentially clean some code up, but refactoring it is haaard. So yea. We can leave switch statements :D

I disagree. With good names you can make a lot of stuff cleaner and with better abstraction. Functions I meant for refactor would be for sure config, and a lil of Stryker.ts - I really do hate double throw. Try catch only place which can throw and log from there.

About names it was general topic. More like - "split up and name stuff".
