### ISSUE TITLE
Add support for overriding config file (individual) properties on cmd line

### ISSUE THREAD

**Issue by ts46235** [stryker-mutator/stryker-js#3016]
WE have an app that has 3 projects in it and in order to run a particular project we have to modify the config file. It would be much more convenient if we could pass in an argument like  `npx run stryker run --configOverride karma.ngConfig.testArguments.project mygoodPrj` so the project would be dynamic.

Maybe there is a way to do that I am not aware of.

thanks!

**Comment by simondel** [comment]
Hi! We support overriding properties, but we don't support overriding nested properties or overriding test runner config. This would be nice to add however!

**Comment by simondel** [comment]
The tool we use to parse command line arguments does not seem to support unknown properties. As a workaround for now, you could create one base `base-stryker.conf.json` and have a custom `stryker.conf.js` for each of your projects with:
```js
const settings = require('./base-stryker.conf.json');
settings.karma.ngConfig.testArguments.project = 'mygoodPrj';
module.exports = settings;
``` 

In order to support nested properties as well as unkown (to the main Stryker process) test runner properties, we would have to do the parsing of the command line arguments manually. @nicojs What are your thoughts on this? This would mean removing the items and their values from NodeJS's `argv` array and parsing them manually (including detecting what kind of type they should have [`boolean`, `string`, `array` etc])
