### ISSUE TITLE
How to fix/workaround the error: "ERROR InitialTestExecutor Initial test run timed out" at Stryker 3? 

### ISSUE THREAD

**Issue by ralves20** [stryker-mutator/stryker-js#3060]
**Question**
Hi!

I'm using Stryker 3 at the project that I work (unfortunately due to some project restrictions I cannot upgrade the stryker version), and when I try to run the stryker, I keep getting this error.

`ERROR InitialTestExecutor Initial test run timed out!`

What can I do to fix or workaround this error?  I saw that there is the "dryRunTimeoutMinutes" but it is not available at stryker 3.3... so how can I workaround this issue on stryker 3?

**Stryker environment**
```
"@stryker-mutator/core": "3.3.1",
"@stryker-mutator/jest-runner": "3.3.1",
"@stryker-mutator/typescript": "3.3.1",
"jest": "24.9.0",
"typescript": "3.2.2"

I'm using the jest runner

**Comment by nicojs** [comment]
How long do regular unit tests take to run?

The only think you can do is to configure jest to run less tests:

```json
{
  "jest": {
    "config": {
      "testMatch": [ "only/one/file.spec.js" ]
    }
  }
}
```

Since you're using Stryker V3, coverage analysis isn't supported for jest (it's `"off"`), so you might want to limit the amount of files being mutates as well, so only the files being tested are mutated.
