### ISSUE TITLE
Add Mutation for "Dropping a statement"

### ISSUE THREAD

**Issue by edi9999** [stryker-mutator/stryker-js#3089]
First, I'm very very impressed by Stryker, it brings so much value to see how robust your code / how well tested it really is. There's been much of badly written tests / insisting on having high test coverage (like a hard limit of 90% or whatever) which was always, in my opinion, very counterproductive to having well-maintained software. What's the best way to support your project (financially or otherwise ?)

**Is your feature request related to a problem? Please describe.**

Yes, I could say so.

In my code, there are some unused properties (or lines of code), that could go undetected by stryker.

Lets take a simple example 

```
class myclasss {
   constructor(foo) {
        this.foo = foo;
   }
   add(a, b) {
      return a + b;
   }
}

// test file : 

expect(new myclass("hello").add(10, 10)).to.equal(20);
```

Stryker will maybe show you that this.foo = "" is a surviving mutant (I'm not sure since I haven't tested it).

Since the codebase that I'm working on has multiple versions and the code has evolved quite a lot, there is a lot of such dead code that might not be detected by Striker. My test suite runs in under a second so I'm interested in having many many mutators to really "stress" my implementation.

**Describe the solution you'd like**

It could be great if mutants could simply drop a particular statement (one line statement maybe).
Maybe it would be complex because there are some statements that cannot be dropped without making the file invalid. For example if you drop a line containing a declaration `const foo = "bar"` and foo is used right afterwards, then of course, the test will fail.

**Describe alternatives you've considered**
Maybe there is a specific tool that would help to detect such issues that does not rely on mutation testing at all. Some kind of static analysis tool (I don't think eslint supports this kind of check).

**Comment by nicojs** [comment]
Thanks for your kind words @edi9999 !

We're currently kind of reluctant to add new mutators. The reason is that all mutators are enabled by default and adding any might have a big impact on performance. That being said, there usually are mutants inside 

We're currently investigating ways to introduce multiple "mutant levels". Level 1 would be fast and loose, level 3 would be very detailed and specific. We could then also allow you to run with "all" mutators active. A student is investigating this a.t.m. but it will take some time for results.  

> What's the best way to support your project (financially or otherwise ?)

Currently spreading the word is all we ask 💖. You're also welcome to contribute of course, [our slack](https://join.slack.com/t/stryker-mutator/shared_invite/enQtOTUyMTYyNTg1NDQ0LTU4ODNmZDlmN2I3MmEyMTVhYjZlYmJkOThlNTY3NTM1M2QxYmM5YTM3ODQxYmJjY2YyYzllM2RkMmM1NjNjZjM) is a good place to start for that. I'll ask my colleagues if we would like to have donations/sponsorship.
