### ISSUE TITLE
Difference between "coverageanalysis" and "enableFindRelatedTests"?

### ISSUE THREAD

**Issue by The-Punk-and-The-Monk** [stryker-mutator/stryker-js#3123]
Hello, I have been using stryker and jest-runner on my project for a while. A great tool for testing code.
But as my code grows, I have to do some optimization on it.
I noticed that there are two params related: 
1.  coverageAnalysis
2. enableFindRelatedTests

The interpretation of two params confusing me. Look like both of them can achieve the goal of only running the test case that covers the mutant.
But, do these two params affect each other?
How could I set the proper value to these two params?
1. coverageAnalysis = perTest; enableFindRelatedTests=true
2. coverageAnalysis = off; enableFindRelatedTests=true
3. coverageAnalysis = perTest; enableFindRelatedTests=false

**Comment by simondel** [comment]
Good question! In case of performance I would expect the following (fastest to slowest):
1. 🚀 coverageAnalysis = perTest; enableFindRelatedTests=false
2. 🏃‍♀️   coverageAnalysis = perTest; enableFindRelatedTests=true
3. 🐌 coverageAnalysis = off; enableFindRelatedTests=true

Stryker's coverage analysis will cause it to skip running tests all together if no matching test is found. This code coverage is calculated once, meaning it will probably be faster than `enableFindRelatedTests` since that has to be done each time tests are executed. This would mean that if you only enable one settings, `coverageAnalysis` would be the way to go.

Since `coverageAnalysis` does most (if not all) work that `enableFindRelatedTests` does, it might make turning both settings on slower than only turning `coverageAnalysis` on.

What are your findings in regards to combining these three options?
