### ISSUE TITLE
Best way to limit stryker to specific files

### ISSUE THREAD

**Issue by hurrtz** [stryker-mutator/stryker-js#3138]
**Question**

Hello team Stryker,

I have successfully implemented stryker in a big react project that uses typescript and jest. The runtime was about 1.5 hours, which is ok, I guess, for the entire project. But considering my workflow I don't want to test the entire project all the time - I want to test the file I am currently working on.

Now, I am quite aware of the `ignorePattern` key in the configuration. That key works fine, of course, when used as described in your latest [strykerjs blogpost](https://stryker-mutator.io/blog/announcing-stryker-js-5-brave-new-dimension.md#%EF%B8%8F-discovering-files) - a combination of `"**"` and `"!src/fileToBeTested.tsx`.

The problem is that the file I want to test might have a plethora of imports, that are dispersed throughout the project. Hence the list of "not-ed" files I have to add manually to the `ignorePattern` array can become quite long, not to speak of the time it takes me to manually find all files required.

That all being said: Is there a way (or planned, maybe) to copy everything and test only what I am telling stryker to test OR to copy only a defined part of my code base but to automatically also copy all missing dependencies?

**Stryker environment**

```
@stryker-mutator/core@5.4.0
│ ├─┬ @stryker-mutator/api@5.4.0
│ ├─┬ @stryker-mutator/instrumenter@5.4.0
│ │ ├── @stryker-mutator/api@5.4.0 deduped
│ │ ├── @stryker-mutator/util@5.4.0 deduped
│ ├─┬ @stryker-mutator/util@5.4.0
├─┬ @stryker-mutator/jest-runner@5.4.0
│ ├── @stryker-mutator/api@5.4.0 deduped
│ ├── @stryker-mutator/util@5.4.0 deduped
├─┬ @stryker-mutator/typescript-checker@5.4.0
│ ├── @stryker-mutator/api@5.4.0 deduped
│ ├── @stryker-mutator/util@5.4.0 deduped
├─┬ stryker-cli@1.0.2
```

```
+-- jest@24.9.0
```

**Comment by simondel** [comment]
Thanks for asking this question! The `ignorePattern` (or the old `files` for that matter) is meant to ensure Stryker has the correct files in its sandbox to run your project successfully (this is one of the reasons we run an initial test run). In your case you don't want to run mutation testing on your entire source code. 

In order to scope the mutation testing to a specific part of your code base, you can use the [mutate](https://stryker-mutator.io/docs/stryker-js/configuration#mutate-string) config setting.

**Comment by hurrtz** [comment]
Wow, that is, of course, the correct answer. Thanks for the quick reply! :)
