### ISSUE TITLE
Initial test run `runInBand` in jest

### ISSUE THREAD

**Issue by Djaler** [stryker-mutator/stryker-js#3233]
**Summary**

I found out that Stryker runs jest with `runInBand: true` option. And this makes initial test run very very slow for me, and it is fails with timeout error because of this. What is the reason to run tests in band?

**Comment by Djaler** [comment]
@nicojs if I understand correctly, runInBand is not needed when `coverageAnalysis: 'off'`, right?

**Comment by Edgpaez** [comment]
@nicojs would you be open to add an optional parameter to the CLI so that one could do:
`stryker run path/to/my-test.js`
?

I see @Djaler's PR improves DX for a mutant check of a subset of files and I think this would be the icing on the cake.

Currently it's `<command> [options] [configFile]` so we'd have to think how (or if) we can remain backwards compatible.

**Comment by nicojs** [comment]
@Edgpaez that would be very breaking and I don't know if it would add a lot.

My guess is that you mean `stryker run path/to/my-source-file-to-mutate.js` rather than `my-test.js`. You can see how this might be confusing without an option flag.

Also, what you want is already supported with the option flag `-m`: `stryker run -m path/to/my-source-file-to-mutate.js`. 

Please open a separate issue if you want to discuss it further.

**Comment by nicojs** [comment]
> @nicojs if I understand correctly, `runInBand` is not needed when `coverageAnalysis: 'off'`, right?

That would be true. If you want, you can create a PR for that case. However, I'm not a big fan. I'm thinking of removing the option to turn off coverage analysis altogether and simply always force `"perTest"`. It would simplify StrykerJS's usage and inner workings a lot.
