### ISSUE TITLE
Do not apply mutation that will do `while (xxx) {}`

### ISSUE THREAD

**Issue by edi9999** [stryker-mutator/stryker-js#3273]
One of the styker-js mutation that is applied is the following : 

![Selection_001](https://user-images.githubusercontent.com/2071336/143459186-89b0f05e-d786-46aa-a648-d750182236b6.png)

However, those kinds of mutation do not make much sense, as `while(xxx) {}` will always either run infinitely or they will not run at all, so it would make more sense to try to completely remove the block including the while.

What do you think ?

My installed versions : 

    "@stryker-mutator/core": "^5.5.0",
    "@stryker-mutator/mocha-runner": "^5.5.0",

**Comment by nicojs** [comment]
Hi @edi9999 , thanks for opening up this issue.

In this case, it doesn't make sense, indeed. However, it is difficult for Stryker to know when these kinds of mutations make sense and when not.

Take this example:

```js
let n = 0;
while (++n < 10) {
  planForWorldDomination();
}
```

As you can see, in this case, mutating the block to an empty block _would_ make sense. 

We're thinking of a better mutator than the block statement mutator, but for now, we would like to keep it as it is.

You might think that running this mutant is expensive, but thanks to #3193, it is actually quite cheap. In the reason field (visible bottom drawer) you should see something like "Hit limit reached". That means that StrykerJS successfully broke out of the timeout and it didn't result in an infinite loop after all.

**Comment by edi9999** [comment]
I'm more "concerned" about my mutation score (I'm at 85% but trying to improve it) :)

But I understand it can be complex to detect this, it could maybe be possible to check if there are any mutations done in the `while` loop, but that would detect only simple things such as (i>0), but obviously it would not work with `while(fnResult())` or lots of other cases.

**Comment by nicojs** [comment]
> But I understand it can be complex to detect this [...]

It's actually impossible to detect all cases because of something called the [halting problem](https://en.wikipedia.org/wiki/Halting_problem). I understand we could hard code some default cases, but I don't think that should be the job of Stryker. Our infinite loop prevention is quite solid. See #3023 for a more detailed explanation of how it works.

> I'm more "concerned" about my mutation score (I'm at 85% but trying to improve it) :)

Don't be concerned 🤗. Timeout and killed mutants are both counted as "detected", which is used for mutation score calculation: `detected / valid * 100`, see [mutant states and metrics](https://stryker-mutator.io/docs/mutation-testing-elements/mutant-states-and-metrics/#metrics).

**Comment by edi9999** [comment]
Ok, I understand, for some reasons I thought that Timedout mutants would lower the mutation score.

**Comment by edi9999** [comment]
Don't know whether I should keep this issue open or not, its up to you.

**Comment by nicojs** [comment]
Good point, in that case close 🤐
