### ISSUE TITLE
Stryker config in vuejs

### ISSUE THREAD

**Issue by marcos-roberto-dev** [stryker-mutator/stryker-js#3325]
**How to make stryker recognize in vue?**

**Stryker environment**

```
+-- @stryker-mutator/core@5.5.1
+-- @stryker-mutator/jest-runner@5.5.1
```

```
+-- vue/test-utils@1.0.3
+-- vue@2.6.1
```

**Additional context**

I've been trying to configure stryker with vue for days, but I get this error, and I don't know what else to do...

```shel
Test runner crashed. Tried twice to restart it without any luck. Last time the error message was: Error: : Configuration error:

Could not locate module @/assets/img/${this.errorHandler.img}.svg mapped as:
/home/marks/Desktop/projects/ServicosAdministrativos/.stryker-tmp/sandbox8065358/src/assets/img/${this.errorHandler.img}.svg.

Please check your configuration for these entries:
{
  "moduleNameMapper": {
    "/^@\/(.*)$/": "/home/marks/Desktop/projects/ServicosAdministrativos/.stryker-tmp/sandbox8065358/src/$1"
  },
  "resolver": null
}
```

**Comment by nicojs** [comment]
Hi @marcos-roberto-dev thanks for opening this issue.

The answer is: it should work. Sometimes the issue is that copying your source code to the sandbox directory is enough to get these errors because of webpack plugins, jest plugins, transpiler plugins, etc

Could you try to run with `--inPlace` 

Did you follow this guide?
https://stryker-mutator.io/docs/stryker-js/guides/vuejs

Can you confirm that `@/assets/img/${this.errorHandler.img}.svg` is part of your code? Of so: Could you create a small reproduction example?
