### ISSUE TITLE
Make it possible to specify which unit test file to run instead of using findRelatedTests

### ISSUE THREAD

**Issue by SmashingQuasar** [stryker-mutator/stryker-js#3595]
**Is your feature request related to a problem? Please describe.**

Currently, you can specify which file to mutate. However, you can't easily specify which unit testing file to run.
This is an issue for multiple reasons:

1 - Let's say you have an OOP code base with a vast number of classes. (For instances, my code base has 545 files). If you want to do mutation tests on such a large code base, it will take many hours (about a day on a MacBook Pro M1). You can't realistically update over 1600 unit tests in one go. This means you will have to work iteratively on each and every test. This means you will need to run Stryker many times to control all the mutants. This makes it near impossible to use Stryker under such conditions for massive code bases. This is especially true with OOP. If you have a base class that is parent to all others, you cannot use "findRelatedTests", because it will trigger every single unit test since they will all use the code from the parent class.

2 - It is less than ideal to test a single file with multiple unit test files. It makes unit testing confusing and difficult to maintain. If you want to make sure `Foo.spec.ts` properly tests `Foo.ts` at 100%, you should be able to run only those two files with Stryker. This is especially true with Functional Programming since functions should be idempotent. It would be suspicious that `Foo.spec.ts` does not test an aspect for `Foo.ts` but `Bar.spec.ts` does. Since you can hardly go through the entire report every time, this kind of situation could be missed easily.

**Describe the solution you'd like**
Right now we have the `-m` option that allows use to specify which files to mutate. Ideally we would have a similar option allowing use to tell which tests to run for those files.

**Describe alternatives you've considered**
It is possible to create a custom script that will run Stryker by creating a temporary Jest configuration file and them remove it. This is a code heavy option and is difficult to maintain in the long run.

**Additional context**
I am using TypeScript and Jest (with SWC) for context.
My code base is OOP but I also have a similar issue when running large FP code bases.

**Comment by nicojs** [comment]
Hi @SmashingQuasar thanks for the detailed issue.

The problem with specifying test files directly through StrykerJS, is that test files are part of the test runner's domain. There are numerous ways test runners allow you to configure it:

- Mocha provides a [`mocha.addFile`](https://mochajs.org/api/mocha#addFile) method.
- Jest has the concept of [`testMatch`](https://jestjs.io/docs/configuration#testmatch-arraystring)
- Karma has a [files array](http://karma-runner.github.io/6.4/config/files.html#files) where you specify all files (not just tests).
- Cucumber uses a [`paths`](https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#finding-your-features) property

There are even test runners [experimenting with adding the tests directly in your source files](https://vitest.dev/guide/in-source.html#setup).

Adding something like a `--testFiles` feature would mean adding support for all officially supported test runners, this adds to the maintenance overhead. It would also complicate things in some use cases because specific test runners often already provide multiple ways to configure the test files. We would be adding to those :/.

@simondel, what do you think?

There is another workaround you can use today, you could choose to add the tests you don't want to the [`--ignorePatterns`](https://stryker-mutator.io/docs/stryker-js/configuration/#ignorepatterns-string).

**Comment by SmashingQuasar** [comment]
That's unfortunate.
I noticed that the `ignorePatterns` is using a `Git` format of expression which are not standard RegExp. Would it be possible to have an option to use standard RegExps? IRRC Git is using a Ruby exclusive RegExp format, it's not very convenient to circumvent the problem I am exposing.
Additionally, I think it would be really cool if we could enable a listing of all detected unit test prior the mutation testing. This would allow experimenting with `ignorePatterns` faster.
It currently takes 50 minutes to run `Stryker` on a single file because it runs the 1600 unit tests over the 400 mutants.

I absolutely love Stryker and find it an amazing tool so I wish we could just go a little bit further to have something incredible. :)

**Comment by nicojs** [comment]
I've got a feeling we are overthinking this. 

Have you taken a look at the [Programmatic API](https://github.com/stryker-mutator/stryker-js/tree/master/packages/core#programmatic-use)?

A small example that might work for you:

<details>
<summary>run-stryker.mjs</summary>

```js
// run-stryker.mjs
import fs from 'fs';
import { Stryker } from '@stryker-mutator/core';

if (process.argv.length < 3) {
  console.error('Usage: node run-stryker.mjs testMatch');
  process.exit(1);
}
async function main() {
  const configText = await fs.promises.readFile(new URL('stryker.conf.json', import.meta.url), 'utf-8');

  /**
   * @type {import('@stryker-mutator/api/core').PartialStrykerOptions}
   */
  const config = JSON.parse(configText);
  config.jest = {
    config: {
      testMatch: process.argv.slice(2),
    },
  };

  const stryker = new Stryker(config);
  await stryker.runMutationTest();
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
```

</details>

Usage: `node run-stryker.mjs "src/**/*.spec.js" "some-other-test-match"`

**Comment by SmashingQuasar** [comment]
That's a pretty good solution actually. I'll just need to tinker around to avoid making Stryker a dependency instead of a devDependency. Thanks for taking time to write this!
I also found a workaround that only works if your test has the same name as your mutated file:
`package.json`:
```json
{
  "scripts": {
    "test:mutation:file:": "stryker run -m ${0} --ignorePatterns *.spec.ts,\!${1}"
  }
}
```

I believe everyone is naming their tests the same name as their tested file so this may be a simple and viable solution. It reduced the mutation time from 1h15m to 11m for the same file. This is from using `findRelatedTests` and using this method.

Thanks for answering so quickly with such detailed answers! ❤️ 

PS: I still believe you should consider relying on standard RegExp rather than Ruby patterns. :P

**Comment by nicojs** [comment]
About the regexp, we could add an `ignoreRegexPatterns` to complement the `ignorePatterns`. However, I don't really see a reason to.

We're currently using [glob](https://www.npmjs.com/package/glob) expressions and they are really quite common in the NodeJS world. 

If you feel like it is needed, feel free to open an issue about it.
