### ISSUE TITLE
Add reporter for importing into SonarQube

### ISSUE THREAD

**Issue by apgrucza** [stryker-mutator/stryker-js#3663]
I would like to be able to import mutation reports into SonarQube. SonarQube can [import third-party issues](https://docs.sonarqube.org/latest/analysis/external-issues/) directly from ESLint JSON and TSLint JSON reports.

The changes required in StrykerJS would be two new reporters (`eslint-json` and `tslint-json`) that use the [ESLint JSON](https://eslint.org/docs/latest/user-guide/formatters/#json) and [TSLint JSON](https://palantir.github.io/tslint/formatters/json/) formats respectively.

In the past, [sonar-stryker-plugin](https://github.com/stryker-mutator/sonar-stryker-plugin) was able to import issues into SonarQube using custom rules. However custom rules were [deprecated in SonarQube 8.9](https://github.com/SonarSource/sonar-custom-rules-examples/tree/master/javascript-custom-rules) in favor of [third-party issues](https://docs.sonarqube.org/latest/analysis/external-issues/), so this plugin no longer works.

Running SonarQube is straightforward using the following guide: https://docs.sonarqube.org/latest/setup/get-started-2-minutes/

**Comment by nicojs** [comment]
Hi @apgrucza thanks for opening this issue.

I wouldn't want to spend time on anything TSLint related since [it has been end of life for years now](https://blog.palantir.com/tslint-in-2019-1a144c2317a9)

As for eslint, it seems like we could do something like this. However, it feels like shoehorning mutation testing results in a linting report. Maybe it would be better for SonarQube to add support for mutation testing. 

We've been developing the [mutation-testing-report-schema](https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/report-schema) for a few years now. This is a JSON file format for mutation testing. The goal is for any mutation testing framework to be able to output this JSON format and there are already implementations for PIT and InfectionPHP and all Stryker frameworks.

Another approach might be to develop a "mutation-testing-json-report-to-eslint-json-report" tool, that can output an eslint JSON report based on a mutation-testing-json report. That way, you would also support all frameworks in 1 go, without needing to change SonarQube.

cc @stryker-mutator/mutation-testing-elements-contributors  what do you think?

**Comment by apgrucza** [comment]
I found that SonarQube has a [generic issue import format](https://docs.sonarqube.org/latest/analysis/generic-issue/) that is better than the linting report formats because it gives you full control over issue fields and values, e.g. `engineId`, `severity` and `effortMinutes`. But it's still shoehorning because data in the mutation testing report would get discarded (e.g. covering tests).

Native support for mutation testing in SonarQube would be ideal, but it [doesn't seem to be on the road map](https://community.sonarsource.com/t/mutation-testing-metrics/28507). At the moment the best we can do is import mutation testing results as "code smell" issues.

I felt that a new reporter would be simplest and easiest-to-use solution, but I take your point about supporting the other mutation testing frameworks in one go.

Translating from one format to another seemed like a good task for [jq](https://stedolan.github.io/jq/), so I created a jq filter that is available [here](https://gist.github.com/apgrucza/9601d409ff878ecc17f99ef37eedc7a9).

**Comment by nicojs** [comment]
Wow! I didn't know about `jq`, but this seems a perfect use case for it, indeed! 

I've got some remarks:

- The `framework` object is optional. StrykerJS provides it, but other mutation testing frameworks might not.
- the `replacement` is also optional. StrykerJS always gives it, but PITTest for example cannot.

I don't know how jq handles errors of missing values.

If you want to contribute this code, you can open a PR at [mutation-testing-elements/](https://github.com/stryker-mutator/mutation-testing-elements/) or write a blog article about it. We would be happy to promote it. You may also write the blog on our own stryker website, it is open source and can be found here: github.com/stryker-mutator/stryker-mutator.github.io/

**Comment by apgrucza** [comment]
I've created a PR here: https://github.com/stryker-mutator/mutation-testing-elements/pull/2044

**Comment by apgrucza** [comment]
Thanks, I've updated the jq filter to better handle missing values and added it to [mutation-testing-elements/](https://github.com/stryker-mutator/mutation-testing-elements/).

Instructions on integrating with SonarQube are now on the website: https://stryker-mutator.io/docs/mutation-testing-elements/sonarqube-integration/

**Comment by nicojs** [comment]
This is very awesome! Thank you! ❤️
