### ISSUE TITLE
Mutator for HTML templates that contain logic ? 

### ISSUE THREAD

**Issue by bodote** [stryker-mutator/stryker-js#3693]
e.g: in Angular HTML-Templates:
```html
<!-- ... -->  
  <ng-container *ngIf="loadingError$ | async as error">
    <div class="alert"> 
     <span id="errorMessage">{{ error }}</span>
<!-- ... -->  
```
Is this even possible ?

**Is your feature request related to a problem? Please describe.**
As I understand Stryker-js , it only mutates javascript or typescript code.
But more often then not, Angular - html-Template also contain logic with e.g. `*ngIf`, `*ngFor`.
Shouldn't we want to mutate those, too ?

**Describe the solution you'd like**
Unfortunately, I understand not enough of Stryker, to imagine a solution.
I am willing to become a Stryker contributor, but where do I start digging ? 

**Describe alternatives you've considered**
No idea...

**Additional context**
none

**Comment by nicojs** [comment]
Great idea! I've thought about that as well. The problem is of course that those mutators would be specific to angular (react, vue, svelte, etc). 

@TeunLamers is working on #2855 and _might_ also be able to mutate the templates. If so, it might make sense to do angular next.

Feel free to take a swing at it. You should look at the [`instrumenter`](https://github.com/stryker-mutator/stryker-js/tree/master/packages/instrumenter) package. It is responsible for generating and placing mutants. StrykerJS uses mutant schemata (aka mutation switching). That should also be supported for any template mutations. See [this blog article for details about that](https://stryker-mutator.io/blog/announcing-stryker-4-mutation-switching/).
