### ISSUE TITLE
404 after clicking the link for the test runner documentation

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#3829]
**Summary**

Clicking the link for the test runner documentation results in a 404 in vscode :/

![test-runner-documentation](https://user-images.githubusercontent.com/1828233/198903389-d7581f56-b066-485d-ab88-ca7b280a041a.gif)

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "_comment": "This config was generated using 'stryker init'. Please take a look at: https://stryker-mutator.io/docs/stryker-js/configuration/ for more information.",
  "packageManager": "npm",
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ],
  "testRunner": "jest",
  "testRunner_comment": "More information about the jest plugin can be found here: https://stryker-mutator.io/docs/stryker-js/jest-runner",
  "coverageAnalysis": "perTest"
}
```

The simplest solution would be rephrasing the sentence to not end with a `.` 🤷‍♂️ 

@Giovds any thoughts?

**Comment by Giovds** [comment]
I agree, That is my bad 🙈 , I'll submit a PR to fix that

**Comment by Giovds** [comment]
I was confused for a second because I was sure I tested on not having a `.` at the end. On the CLI (Windows Terminal) it makes URLs clickable differently so I didn't run into this issue. VScode actually thinks the `"` ending the string is part of the URL. I'd suggest rephrasing it something like: `  "testRunner_comment": "Please take a look at https://stryker-mutator.io/docs/stryker-js/jest-runner for information about the jest plugin.",`
