### ISSUE TITLE
How To Use Existing Coverage?

### ISSUE THREAD

**Issue by PythooonUser** [stryker-mutator/stryker-js#4133]
**Question**

I would like to know how I can use existing coverage that has been generated before.

I'm running `$ npm run test:unit` which spins up `jest`. This generates a coverage report.

Then I'm running `$ npm run test:mutation` which runs `jest` AGAIN to get the coverage information. Seems wasteful as I've already done it.

I'm new to `stryker`, but I have used PHP Infection before and it allows to use an existing coverage report and I assumed it would work the same here, but it doesn't as far as I can see.

With `stryker` is the workflow changed in such a way that I don't need to run my unit tests manually anymore?

**Stryker environment**

```
├── @stryker-mutator/core@6.4.2
├── @stryker-mutator/jest-runner@6.4.2
├── @stryker-mutator/typescript-checker@6.4.2
├── stryker-cli@1.0.2
```

```
├── jest@29.5.0
├── ts-jest@29.1.0
└── typescript@5.0.4
```

**Additional context**

I'm on Windows.

```json
// package.json

{
  "scripts": {
    "test:unit": "jest",
    "test:mutation": "stryker run",
    "test": "npm run test:unit && npm run test:mutation"
  }
}
```

Ideally, my pipeline fails when
- tests fail
- coverage is too low
- mutation score is too low

Stryker Output:

```
15:37:30 (25616) INFO ProjectReader Found 61 of 335 file(s) to be mutated.
15:37:31 (25616) INFO Instrumenter Instrumented 61 source file(s) with 801 mutant(s)
15:37:31 (25616) INFO ConcurrencyTokenProvider Creating 15 test runner process(es).
15:37:34 (25616) INFO DryRunExecutor Starting initial test run (jest test runner with "perTest" coverage analysis). This may take a while.
15:37:42 (25616) INFO DryRunExecutor Initial test run succeeded. Ran 141 tests in 7 seconds (net 368 ms, overhead 6728 ms).
```

**Comment by danny12321** [comment]
Hi @PythooonUser,

Stryker always runs a initial test run because it needs to know that all tests passes (with the current stryker config). If a test does fail is throws the following error: 
![image](https://user-images.githubusercontent.com/15829978/235140736-95b82050-fba7-4672-9b2b-3fcae6dd802e.png)

This means that could skip running the script `test:unit` before running stryker.

I don't think it is possible to let the pipeline fail when the test coverage is to low by only running Stryker, but I guess that the mutation score will probably low to if the test coverage is low.

**Comment by PythooonUser** [comment]
Okay, I understand that it's currently not supported.

I can draw from an example of [PHP Infection Docs](https://infection.github.io/guide/command-line-options.html#skip-initial-tests):

![image](https://user-images.githubusercontent.com/13063023/235152085-0831b333-59da-44b5-ac12-66a03531ba25.png)

It's a flag that everyone must use on its own risk, but can speed up performance quite substantially. Maybe it's worth investigating?

Or do we alter the test run with the Stryker config in such a way that we can't rely on existing coverage?

**Comment by danny12321** [comment]
My experience is that when an incorrect Stryker config is used most of the times no test will be found or a runtime error will be thrown. So maybe it won't be a problem at all. 

I think it is something we would like to invest time in, but it would be pretty time consuming because it needs to be implemented for every test runner.

The only concerns I have are:
- How do we ensure the coverage is up to date?
- Could Stryker config change the coverage data?
- Does it improve a realistic working environment? When the coverage data is out of date it would still needs to be updated, so it is only useful when Stryker runs multiple times in a row or when the tests have already ran which seems like a realistic scenario in a pipeline.

**Comment by PythooonUser** [comment]
> How do we ensure the coverage is up to date?

We don't? It would be up to the developer to make sure, not Stryker. I imagine this running in a pipeline and when unit tests fail the mutation tests are not even run.

> Could Stryker config change the coverage data?

No idea. I hope not? Coverage should ideally be something universal, but maybe different algorithms can get to different conclusions.

> Does it improve a realistic working environment?

I guess so. Unit tests alone run in a project of mine for 8-10 minutes, as we have ~1800 files in there. Not needing to run that twice is a time saver for sure (in that case though mutation tests would run for hours?^^).

But I get that it would require a lot of effort from your side, and nobody has asked for that kind of feature before (as far as I know), so I assume for most of the devs unit tests run sufficiently fast 🤷

**Comment by nicojs** [comment]
As @danny12321 already mentioned, indeed Stryker uses the initial test run to make sure your unit tests pass, but more critical, Stryker uses _its own coverage analytics_. It doesn't rely on `lcov.info` or something like that.

There are multiple reasons for this:
1. Stryker mutates your code using something called ["mutant schemata" (or mutation switching)](https://stryker-mutator.io/blog/mutation-switching/). This is also referred to as "instrumentation" in StrykerJS logs. After it did that, the lines and columns will be different. It is much easier for us to add coverage instrumentation during this instrumentation phase than to rely on the coverage analysis of the specific test runner.
2. Stryker needs to know the coverage analysis _per test_. This is done by collaborating with StrykerJS's instrumentation and the test runner plugin. 

That being said, you might be helped by a faster initial test run. We always run the initial test run in a single test runner (we run jest with `--runInBand`). We could think of ways to improve the initial test run speed by using concurrent test runners, as we do during the mutation testing stage.

**Comment by PythooonUser** [comment]
Thanks @nicojs for your extended answer!

I understand that we have additional complexity here because Stryker uses its own coverage format and processing.

Maybe it makes sense to add a small note about this on the docs?

Either way, I will close this issue now. My question got answered. Thanks again :)
