### ISSUE TITLE
Question to speed up tests execution

### ISSUE THREAD

**Issue by ArnaudBuchholz** [stryker-mutator/stryker-js#4142]
**Question**

I try to organize my tests so that each file is associated to a spec one. For instance, `add.ts` is associated with `add.spec.ts`.
My will would be that the spec file fully covers the source one. Hence, if a mutation occurs in the source, I would assume that running its spec file is enough to detect it.

My understanding of the current execution scheme is that **all** tests are executed for every mutant. Is it true ?
If so, would it be possible to add an option to restrict the tests execution to the associated spec file ?

**Stryker environment**

```
    "@stryker-mutator/core": "^6.4.2",
    "@stryker-mutator/jest-runner": "^6.4.2",
    "@stryker-mutator/typescript-checker": "^6.4.2",
```

```
    "jest": "^29.5.0",
```

**Additional context**

https://github.com/progbots/engine

**Comment by nicojs** [comment]
Thanks for supplying a link to the repo. Since the jest test runner plugin currently doesn't support hot reload (see #3455), it relies on jests `--findRelatedTests` feature to filter test files to load. Since you've disabled that in your Stryker config, it loads all test files for each mutant.

It should still only run the tests that actually cover a mutant, but the heavy lifting of loading the file is already done by that point. 

Is there a way you could make `jest --findRelatedTests` work? See also https://stryker-mutator.io/docs/stryker-js/troubleshooting/#mutants-survive-but-should-be-killed---jest-runner for a possible work around for you.

**Comment by ArnaudBuchholz** [comment]
Very good point, I remember disabling this feature in another project so I just copied the setting here too. I will remove it to see if it works. Thanks for the prompt answer (and this amazing tool).

**Comment by ArnaudBuchholz** [comment]
So I removed the settings and ran the mutation tests again (I even tried setting it to `true`).
The results and performance are still the same : same number of tests ran per mutant on average.

**Comment by emir7** [comment]
Maybe something that could help you reduce the amount of tests that are being executed is described at: https://stryker-mutator.slack.com/archives/CTYUW4B0E/p1681306803311799 where you can specify a function that defines how jest resolves it dependencies

**Comment by mkizka** [comment]
@ArnaudBuchholz 

Hello. I had the same problem. In my case, `dependencyExtractor` can solve this.
ref: https://github.com/jestjs/jest/issues/14000

`--findRelatedTests` usually returns a lot of tests due to complex dependencies.

```
$ npx jest --findRelatedTests operators/add.ts --listTests
/home/ubuntu/workspace/engine/state/State.spec.ts
/home/ubuntu/workspace/engine/state/callstack.spec.ts
/home/ubuntu/workspace/engine/state/MemoryTracker.spec.ts
/home/ubuntu/workspace/engine/objects/Array.spec.ts
/home/ubuntu/workspace/engine/state/parser.spec.ts
/home/ubuntu/workspace/engine/operators/get.spec.ts
/home/ubuntu/workspace/engine/operators/set.spec.ts
/home/ubuntu/workspace/engine/operators/throw.spec.ts
/home/ubuntu/workspace/engine/objects/dictionaries/Dictionary.spec.ts
/home/ubuntu/workspace/engine/operators/add.spec.ts
...
/home/ubuntu/workspace/engine/operators/count.spec.ts
```

For example, by setting the `dependencyExtractor` as follows, it will return the only associated spec file.

```js
// jest.config.js
module.exports = {
  ...
  dependencyExtractor: "<rootDir>/dependencyExtractor.js",
};

// dependencyExtractor.js
const crypto = require("crypto");
const fs = require("fs");

module.exports = {
  extract(code, filePath, defaultExtract) {
    if (filePath.endsWith(".spec.ts")) {
      const set = new Set();
      set.add(filePath.replace(".spec.ts", ".ts"));
      return set;
    }
    return new Set();
  },
  getCacheKey() {
    return crypto
      .createHash("md5")
      .update(fs.readFileSync(__filename))
      .digest("hex");
  },
};

```

```
$ npx jest --findRelatedTests operators/add.ts --listTests
/home/ubuntu/workspace/engine/operators/add.spec.ts
```

As a result, the number of tests is reduced, and mutation testing can speed up. Note that mutation scores may decrease.

**Comment by nicojs** [comment]
Exactly. As @mkizka points out, you can use jest to first debug the findRelatedTest issue. Once you've got that covered, Stryker should run optimally

**Comment by ArnaudBuchholz** [comment]
Awesome, thx guys, I will try that.
@nicojs I was also wondering if there is a way to leverage the ` __stryker__` structure to know which mutation is enabled in which file ? this way I could condition the `describe` to be skipped :-)

**Comment by nicojs** [comment]
I don't think so, the file name isn't stored there. 

1. You are probably already too late by that point anyways, since the heavy lifting is already done (transforming and loading). 
1. The `it`s without coverage will be skipped using a spec filter, so that should yield as much performance as skipping `describe`s.

**Comment by ArnaudBuchholz** [comment]
Last update (and I will close this issue) : the `dependencyExtractor` works like a charm : from 30 minutes down to 2.
Yet, I have some adjustments to do but the methods opens lots of door I will explore.
Thanks @nicojs and @mkizka for your help on that matter, very valuable !
